[workspace]
name = "fmask"
version = "5.0.2"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies]
python = ">=3.10"
gdal = "*"
libgdal-jp2openjpeg = "*"
rasterio = "*"
numpy = "*"
scipy = "*"
pandas = "*"
scikit-image = "*"
scikit-learn = "*"
pytorch = "*"
matplotlib = "*"
plotly = "*"
nbformat = "*"
pyproj = "*"
click = "*"
lxml = "*"
geopandas = "*"
lightgbm = "*"
utm = "*"
segmentation-models-pytorch = "*"

[package]
name = "fmask"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
