[workspace]
name = "fmask"
version = "5.0.1"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]
conda-pypi-map = { conda-forge = "conda-pypi-map.json" }

[dependencies]
python = ">=3.10"
gdal = "*"
libgdal-jp2openjpeg = "*"
rasterio = "*"
numpy = ">=1.22"
scipy = "*"
pandas = "*"
scikit-image = "*"
scikit-learn = "*"
pytorch = "*"
matplotlib = "*"
plotly = "*"
nbformat = "*"
pyproj = "*"
click = "*"
lxml = "*"
geopandas = "*"
lightgbm = "*"
utm = "*"
segmentation-models-pytorch = "*"

[pypi-dependencies]
fmask = { path = ".", editable = true }

[package]
name = "fmask"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
